group: travis_latest
language: python
python:
  - 2.7
  - 3.6
matrix:
  allow_failures:
    - python: 3.6
install:
  - pip install --upgrade pip
  - pip install flake8 pytest
  - pip install -r requirements.txt
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F822 --show-source --statistics
  # TODO: add this F821 test to the line above once they have been fixed
  - flake8 . --count --exit-zero --select=F821 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script: true #  pytest
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
